apiVersion: v1
kind: Service
metadata:
  name: kuweb-service
spec:
  #type: ClusterIP
  type: NodePort
  selector:
    app: kuweb-label
  ports:
  - port: 8080
    targetPort: 8080
    # port 번호를 랜덤이 아닌 지정하고 싶은 경우 사용
    nodePort: 30029
